@startuml

Resource <|-- Device
ResourceManager "1" *-- "many" Resource : contains

interface Resource {
    +get_index() : std::uint32_t
}

class Device {
    +get_index() override: std::uint32_t
}

class ResourceManager{
    +get_resource(std::uint32_t index) : Resource::Ptr
    -std::vector<Resource::Ptr> resources
}

@enduml
